.run '/net/faculty-1/jd/Angst/Code/readdolphot.pro'
.run '/net/faculty-1/jd/Angst/Code/readdolfake.pro'
.run '/net/faculty-1/jd/Angst/Code/restoreregion.pro'
.run '/net/faculty-1/jd/Angst/Code/make_xarray.pro'
.run '/net/faculty-1/jd/Angst/Code/make_yarray.pro'
.run '/net/faculty-1/jd/Angst/Code/hist_nd.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/editpoints.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/mindist_from_poly.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/suspectprofpts.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/ellipsefit_fixedcen.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/ellipsefit.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/densprofile.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/makedensitymap.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/makecorrecteddensitymap.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/plotdensmap.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/plotprof_sbonly.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/overplotprof_sbonly.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/overplotallsurfprof.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/generatealldensmaps.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/generatesurfprof.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/reconstructstellarmap.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/reconstructdensmap.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/makeradialcmd.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/interpolate_metallicity.pro'
.run '/net/faculty-1/jd/Angst/Code/DensMap/plot_rgb_isochrones_fixedZ.pro'
;
file='/local/jd/Angst/Phot/KDG73_ap1_fs2_frc1.bi2.fits'
isofile12 = '/net/faculty-1/jd/Angst/Isochrones/Girardi07/rgb_isochrones_12Gyr.dat'
isofile10 = '/net/faculty-1/jd/Angst/Isochrones/Girardi07/rgb_isochrones_10Gyr.dat'
isofile8 = '/net/faculty-1/jd/Angst/Isochrones/Girardi07/rgb_isochrones_8Gyr.dat'
isofile6 = '/net/faculty-1/jd/Angst/Isochrones/Girardi07/rgb_isochrones_6Gyr.dat'
isofile4 = '/net/faculty-1/jd/Angst/Isochrones/Girardi07/rgb_isochrones_4Gyr.dat'
stars = readdolphot(file)



